### ISSUE TITLE
Sometimes driver wont work 'Invalid device pointer. Aborting!'

### ISSUE THREAD

**Issue by lfzawacki** [FrotBot/SwitchProConLinuxUSB#28]
I'm not sure what causes this, I had this driver working for a few days in a row. But right now when running the code it always returns 'Invalid device pointer. Aborting!'

The controller has the home button stuck with the blue LED on, apart from that I have no more context or additional debugging information to provide.

**Comment by hluaces** [comment]
This has happened to me today.

I simply disconnected the controller, pressed the "sync" button so that the light turned off and plugged it back again. After doing this I executed the driver as root and it seemed to work ok.

Beware with bluetooth. If you have a device synced with the controller some odd things might happen. At the beggining I was powering up my Steam link without realising it.

**Comment by lfzawacki** [comment]
I forgot to update it here, but I got a consistent way of making it work again. Just like @hluaces said, I disconnect the controller and press the sync button to turn it off and try again. It sometimes takes a few tries, but eventually the controller is working again.
